version: "3.7"

services:
  lb4-app:
    image: node:20 # Replace with your LoopBack 4 Docker image name
    container_name: lb4-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_NAME: webhoster
    networks:
      - internalnet

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: webhoster
    volumes:
      - ./database/m2_webhoster.sql:/docker-entrypoint-initdb.d/m2_webhoster.sql
    restart: always
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
